import React from 'react'

export const facebookURL = 'https://facebook.com'
export const youtube = 'https://youtube.com'
export const twitter = 'https://twitter.com'
export const linked = 'https://linked.com'
export const jsHistoryHome = '#home'
export const jsHistoryTimeline = '#timeline'
export const jsHistoryPossibilities = '#possibilities'
export const jsHistoryTrend = '#trend'
export const task01 = 'task01'
export const mainPage = '/'
