import React from 'react'

export const FacebookURL = 'https://facebook.com'
export const Youtube = 'https://youtube.com'
export const Twitter = 'https://twitter.com'
export const Linked = 'https://linked.com'
export const JsHistoryHome = '#home'
export const JsHistoryTimeline = '#timeline'
export const JsHistoryPossibilities = '#possibilities'
export const JsHistoryTrend = '#trend'
export const Task01 = 'task01'
export const MainPage = '/'
